version: "3"

services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /output_logs:/volume
    networks:
      - SuselNetwork

  apache:
    build: ./apache
    restart: always
    ports:
      - 8090:8090
    networks:
      - SuselNetwork

networks:
  SuselNetwork:
